# Standard HTTP port, as Spring Boot MVC wants to use 8080 by default.
server.port: 80

db:
  host: localhost
  port: 3306
  name: senie
  user: senie
  pass: senie

spring:
  datasource:
    url: jdbc:mysql://${db.host}:${db.port}/${db.name}
    username: ${db.user}
    password: ${db.pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

logging:
  level:
    lv.ailab: TRACE # Maximum possible log level for our code.
  # Shorter and cleaner log format.
  pattern.console: "[%d{yyyy-MM-dd'T'HH:mm:ssXXX}][%5p][%42c{42}] %message%n%ex{0}"
