# Standard HTTP port, as Spring Boot MVC wants to use 8080 by default.
server.port: 80

logging:
  level:
    lv.tezaurs: TRACE # Maximum possible log level for our code.
  # Shorter and cleaner log format.
  pattern.console: "[%d{yyyy-MM-dd'T'HH:mm:ssXXX}][%5p][%42c{42}] %message%n%ex{0}"
